Moved PHP installer script to pre-install.php wrote bash wrapper script for pre-install that calls pre-install.php.

diff --git a/src/lib/pre-install b/src/lib/pre-install
--- a/src/lib/pre-install
+++ b/src/lib/pre-install
@@ -1,76 +1,24 @@
-#! /usr/bin/env php
-<?php
+#!/usr/bin/env bash
 
-$OLD_PWD = $_SERVER['PWD'];
+pushd `dirname $0` > /dev/null 2>&1;
 
-// work from lib directory
-chdir(dirname($argv[0]));
+PHP_BIN=`which php`;
 
-if ($argv[0] === './pre-install.php' || $_SERVER['PWD'] !== $OLD_PWD) {
-	// pwd doesn't resolve symlinks
-	$LIB_DIR = $_SERVER['PWD'];
-} else {
-	// windows doesn't update $_SERVER['PWD']...
-	$LIB_DIR = getcwd();
-}
-$APP_DIR = dirname($LIB_DIR);
-$CONFIG_FILE = '../conf/config.ini';
-$APACHE_CONFIG_FILE = '../conf/httpd.conf';
+if [ -z "$PHP_BIN" ]; then
+	# Try /usr/local/bin/php
+	PHP_BIN='/usr/local/bin/php';
 
-// work from lib directory
-chdir($LIB_DIR);
-// set default timezone
-date_default_timezone_set('UTC');
+	if [ ! -x "$PHP_BIN" ]; then
+		read -p 'PHP executable not found. Enter path to php: ' PHP_BIN;
+	fi
+fi
 
+if [ -x "$PHP_BIN" ]; then
+	$PHP_BIN ./pre-install.php
+else
+	echo 'PHP executable not found, unable to run pre-install.php';
+	exit 1;
+fi
 
-// setup configuration defaults and help
-
-$DEFAULTS = array(
-	'APP_DIR' => $APP_DIR,
-	'DATA_DIR' => str_replace('/apps/', '/data/', $APP_DIR),
-	'MOUNT_PATH' => '/webabsolutes',
-	'SQLITE_DB' => 'testdata.db',
-	'AUTH_FILE' => $APP_DIR . '/conf/users.htpasswd'
-);
-
-$HELP_TEXT = array(
-	'APP_DIR' => 'Absolute path to application root directory',
-	'DATA_DIR' => 'Absolute path to application data directory',
-	'MOUNT_PATH' => 'Url path to application',
-	'SQLITE_DB' => 'Name of Sqlite Database file (within data directory)',
-	'AUTH_FILE' => 'Name of htpassword authorization file'
-);
-
-
-// interactively configure
-
-include 'configure.php';
-
-
-// output apache configuration
-
-file_put_contents($APACHE_CONFIG_FILE, '
-	# auto generated by ' . __FILE__ . ' at ' . date('r') . '
-	Alias ' . $CONFIG['MOUNT_PATH'] . ' ' . $CONFIG['APP_DIR'] . '
-	<Location ' . $CONFIG['MOUNT_PATH'] . '>
-		Order Allow,Deny
-		Allow from all
-
-		# This authorization file can be created on *nix systems using:
-		#   htpasswd -c users.passwd <username>
-		# You will be prompted for the password
-
-		AuthType Basic
-		AuthName \'Authorization Required\'
-		AuthBasicProvider file
-		AuthUserFile ' . $CONFIG['AUTH_FILE'] . '
-		Require valid-user
-	</Location>
-	RewriteRule ^${MOUNT_PATH}/observation_data/(.*)\$ /observation_data.php?id=\$1 [L,PT]
-	RewriteRule ^${MOUNT_PATH}/observatory_detail_feed/(.*)\$ /observatory_detail_feed.php?id=\$1 [L,PT]
-	RewriteRule ^${MOUNT_PATH}/observatory_summary_feed\$ /observatory_summary_feed.php [L,PT]
-	RewriteRule ^${MOUNT_PATH}/observation/\$ /observation.php?id=\$1 [L,PT]
-	RewriteRule ^${MOUNT_PATH}/observatory/\$ /observatory.php?id=\$1 [L,PT]
-');
-
-
+popd > /dev/null 2>&1;
+exit 0;
